openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/inventory/product/{slug}:
    get:
      operationId: retrieveProductSerializers
      description: ''
      parameters:
      - name: slug
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
          description: ''
      tags:
      - api
  /api/v1/inventory/all-products:
    get:
      operationId: listProducts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
          description: ''
      tags:
      - api
    post:
      operationId: createProduct
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Products'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Products'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Products'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
          description: ''
      tags:
      - api
  /api/v1/inventory/new-product:
    post:
      operationId: createProductSerializers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Products'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Products'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Products'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
          description: ''
      tags:
      - api
  /api/v1/inventory/new-review:
    post:
      operationId: createReviewSerializers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reviews'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Reviews'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Reviews'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reviews'
          description: ''
      tags:
      - api
components:
  schemas:
    Products:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        url:
          type: string
          readOnly: true
        description:
          type: string
          maxLength: 255
        category:
          enum:
          - toys
          - foods
          - cosmetics
          - fashion
          type: string
        price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100000
          minimum: -100000
        date:
          type: string
          format: date
          readOnly: true
        images:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              image:
                type: string
                format: binary
              product:
                type: integer
            required:
            - image
            - product
          readOnly: true
        reviews:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              rating:
                type: integer
                maximum: 5
                minimum: 0
              review:
                type: string
                maxLength: 255
              date:
                type: string
                format: date
                readOnly: true
              product:
                type: integer
            required:
            - rating
            - review
            - product
          readOnly: true
        uploaded_images:
          type: array
          items:
            type: string
            format: binary
          writeOnly: true
      required:
      - name
      - description
      - category
      - price
      - uploaded_images
    Reviews:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        rating:
          type: integer
          maximum: 5
          minimum: 0
        review:
          type: string
          maxLength: 255
        date:
          type: string
          format: date
          readOnly: true
        product:
          type: integer
      required:
      - rating
      - review
      - product
