# Generated by Django 4.0.6 on 2023-04-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartServiceDRF', '0005_alter_cartitem_cart_alter_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.CharField(max_length=500),
        ),
    ]
