openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/accounts/buyer/shipment/{uuid}:
    get:
      operationId: retrieveBuyerShipmentAddressSerializers
      description: ''
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuyerShipmentAddresss'
          description: ''
      tags:
      - api
  /api/v1/accounts/seller/all:
    get:
      operationId: listSellerProfiles
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SellerProfiles'
          description: ''
      tags:
      - api
  /api/v1/accounts/seller/profile/{uuid}:
    get:
      operationId: retrieveSellerProfileSerializers
      description: ''
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SellerProfiles'
          description: ''
      tags:
      - api
  /api/v1/accounts/auth/register/seller:
    post:
      operationId: createcreate_seller
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/accounts/auth/register/buyer:
    post:
      operationId: createcreate_buyer
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/accounts/auth/login:
    post:
      operationId: createuser_login
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/accounts/auth/logout:
    post:
      operationId: createlogout_view
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/v1/accounts/buyer/create-shipment:
    post:
      operationId: createBuyerShipmentAddressSerializers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuyerShipmentAddresss'
          description: ''
      tags:
      - api
  /api/v1/accounts/seller/create-profile:
    post:
      operationId: createSellerProfileSerializers
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SellerProfiles'
          description: ''
      tags:
      - api
  /api/v1/accounts/buyer/shipment/{user}/edit:
    put:
      operationId: updateBuyerShipmentAddress
      description: ''
      parameters:
      - name: user
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuyerShipmentAddresss'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateBuyerShipmentAddress
      description: ''
      parameters:
      - name: user
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BuyerShipmentAddresss'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuyerShipmentAddresss'
          description: ''
      tags:
      - api
  /api/v1/accounts/seller/profile/{user}/edit:
    put:
      operationId: updateSellerProfile
      description: ''
      parameters:
      - name: user
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SellerProfiles'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateSellerProfile
      description: ''
      parameters:
      - name: user
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SellerProfiles'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SellerProfiles'
          description: ''
      tags:
      - api
  /api/v1/accounts/buyer/shipment/{user}/delete:
    delete:
      operationId: destroyBuyerShipmentAddress
      description: ''
      parameters:
      - name: user
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/accounts/seller/profile/{user}/delete:
    delete:
      operationId: destroySellerProfile
      description: ''
      parameters:
      - name: user
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    BuyerShipmentAddresss:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        url:
          type: string
          readOnly: true
        phone_no:
          type: string
          maxLength: 11
        phone_no_2:
          type: string
          nullable: true
          maxLength: 11
        country:
          type: string
          maxLength: 55
        state:
          type: string
          maxLength: 55
        city:
          type: string
          maxLength: 55
        street:
          type: string
          maxLength: 55
        user:
          type: string
      required:
      - phone_no
      - country
      - state
      - city
      - street
      - user
    SellerProfiles:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        cac_reg_no:
          type: string
          maxLength: 20
        product_category:
          enum:
          - toys
          - foods
          - cosmetics
          - fashion
          type: string
        location:
          type: string
          maxLength: 150
        contact_no:
          type: string
          maxLength: 11
        user:
          type: string
      required:
      - cac_reg_no
      - product_category
      - location
      - contact_no
      - user
