# Generated by Django 4.0.6 on 2023-03-23 12:55

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_buyerpaymentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerpaymentinformation',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='buyerpaymentinformation',
            name='expiry_date',
            field=models.CharField(max_length=7, validators=[accounts.models.BuyerPaymentInformation.validate_expiry_date]),
        ),
        migrations.AlterField(
            model_name='buyerpaymentinformation',
            name='payment_method',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='buyerpaymentinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyershipmentaddress',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='buyershipmentaddress',
            name='phone_no_2',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='contact_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
