# Generated by Django 4.0.6 on 2023-03-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.CharField(max_length=80),
        ),
    ]
