# Generated by Django 4.0.6 on 2023-05-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingServiceDRF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='1', max_length=50),
        ),
    ]
