# Generated by Django 4.0.6 on 2023-05-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingServiceDRF', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
