# Generated by Django 3.2.3 on 2022-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='location',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
