# Generated by Django 4.0 on 2022-11-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
