# Generated by Django 3.2.3 on 2023-03-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230301_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='location',
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='cac_reg_no',
            field=models.CharField(default='00000000000', max_length=20, unique=True),
        ),
    ]
