# Generated by Django 4.0.6 on 2023-03-16 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230303_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerShipmentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=11)),
                ('phone_no_2', models.CharField(max_length=11, null=True)),
                ('country', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('street', models.CharField(max_length=55)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cac_reg_no', models.CharField(max_length=20, unique=True)),
                ('product_category', models.CharField(choices=[('toys', 'toys'), ('foods', 'foods'), ('cosmetics', 'cosmetics'), ('fashion', 'fashion')], max_length=9)),
                ('location', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='producerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConsumerProfile',
        ),
        migrations.DeleteModel(
            name='ProducerProfile',
        ),
    ]
